### ISSUE TITLE
Error in ide/examples/vscode/tasks.json

### ISSUE THREAD

**Issue by Rosi2143** [openhab/openhab-docs#1287]
when trying to read the file [tasks.json](https://raw.githubusercontent.com/openhab/openhab-docs/master/developers/ide/examples/vscode/tasks.json) with python3 json package the following error is returned, due to an extra comma in line 83.

```
Traceback (most recent call last):
  File "./start_vscode_addon.py", line 105, in <module>
    task_data = json.load(fin)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 83 column 13 (char 2367)
```

**Comment by Confectrician** [comment]
Fixed in #1288
