### ISSUE TITLE
Docu Windows Update

### ISSUE THREAD

**Issue by FrederikNT** [openhab/openhab-docs#244]
I followed the new description how to update openhab on http://docs.openhab.org/installation/windows.html

Running the start.bat ´does not start openhab and I get following errors:
```
Launching the openHAB runtime...
karaf.bat: Ignoring predefined value for KARAF_HOME
WARN: file:/C:/openhab-offline/userdata/etc/config.properties is not found, so not loaded
null
WARN: file:/C:/openhab-offline/userdata/etc/config.properties is not found, so not loaded
Error occurred shutting down framework: java.lang.NumberFormatException: null
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.apache.karaf.main.ConfigProperties.<init>(ConfigProperties.java:208)
        at org.apache.karaf.main.Main.updateInstancePidAfterShutdown(Main.java:226)
        at org.apache.karaf.main.Main.main(Main.java:191)
```

Something must be wrong in the description

NoTechi

**Comment by ThomDietrich** [comment]
@FrederikNT sorry for not getting back to you earlier. Did you try not deleting `C:/openhab-offline/userdata/etc/config.properties`? Would be great to find a solution for your problem...
